name: siri_shortcuts
description: A Flutter plugin to add user interactivity with Siri Shortcuts.
version: 0.0.1
homepage: https://acmesoftware.com

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  pigeon: ^4.2.5

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SiriShortcutsPlugin
      macos:
        pluginClass: SiriShortcutsPlugin
