name: siri_shortcuts
description: A Flutter plugin to add user interactivity with Siri Shortcuts.
version: 1.0.0
homepage: https://acmesoftware.com

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  pigeon: ^13.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SiriShortcutsPlugin
      macos:
        pluginClass: SiriShortcutsPlugin
